if Rails.env.development?
  User.destroy_all
  Project.destroy_all
  Agreement.destroy_all
  Role.destroy_all
  
  names = { "The Boss" => "boss@boss.com", "regina" => "regina@regina.com", "peter" => "peter@peter.com", "homer" => "homer@homer.com",
            "elmer" => "elmer@elmer.com", "stewey"=> "stewey@stewey.com", "betty" => "betty@betty.com", 
            "bob" => "bob@bob.com", "lisa" => "lisa@lisa.com" }
  names.each { |name, email|  User.create name: name, email: email, role: rand(1..5), password: "tree", password_confirmation: "tree" }
  client = Client.create name: "Client", email: "Client@client.com"
  
  
  rand(1000..5000)
  
  Project.create title: "Rails Project", client_email: client.email, client_id: client.id, is_active: true, project_amount: rand(1000..5000)
  Project.create title: "WordPress Project", client_email: client.email, client_id: client.id, is_active: true, project_amount: rand(1000..5000)
  Project.create title: "Design Project", client_email: client.email, client_id: client.id, is_active: true, project_amount: rand(1000..5000)
  Project.create title: "Beer and Donuts Project", client_email: client.email, client_id: client.id, is_active: true, project_amount: rand(1000..5000)
  
  projects = Project.all
  project_manager = User.find_by_name("The Boss")
  
  projects.each do |project|
    Agreement.create title: "Project Manager", description: "I'm in charge of everything", 
                     content: "I'll do such and such, make sure such and such is great, and I'll also provide the beer and donuts",
                     user_id: project_manager.id, project_id: project.id, is_admin: true, user_amount: 1000, is_active_admin: false, is_active_admin: false
    end
    
        Role.create classification: 1, description:"Web Developer"
        Role.create classification: 2, description:"Web Designer"
        Role.create classification: 3, description:"UX"
        Role.create classification: 4, description:"Content Specialist"
        Role.create classification: 5, description:"Sales & Business"
        
        
puts "BE BRAVE GENTLEMEN. THIS GUILD ISN'T GOING TO BUILD ITSELF...oh, and also, data has been added"
end
                                                                                              
  # Role.create classification:"0510", description:"Accounting                                        "
  #   Role.create classification:"0525", description:"Accounting Technician                             "
  #   Role.create classification:"1510", description:"Actuary                                           "
  #   Role.create classification:"1898", description:"Admeasurement                                     "
  #   Role.create classification:"0399", description:"Administrative and Office Support Student Trainee "
  #   Role.create classification:"0341", description:"Administrative Officer                            "
  #   Role.create classification:"0861", description:"Aerospace Engineering                             "
  #   Role.create classification:"1981", description:"Agricultural                                      "
  #   Role.create classification:"0471", description:"Agriculture Extension                             "
  #   Role.create classification:"5306", description:"Agronomy                                          "
  #   Role.create classification:"5415", description:"Air Conditioning Equipment                        "
  #   Role.create classification:"2183", description:"Air Conditioning Equipment Operating              "
  #   Role.create classification:"1815", description:"Air Navigation                                    "
  #   Role.create classification:"2154", description:"Air Safety Investigating                          "
  #   Role.create classification:"2152", description:"Air Traffic Assistant                             "
  #   Role.create classification:"8862", description:"Air Traffic Control                               "
  #   Role.create classification:"2892", description:"Aircraft Attending                                "
  #   Role.create classification:"8602", description:"Aircraft Electrician                              "
  #   Role.create classification:"8840", description:"Aircraft Mechanic                                 "
  #   Role.create classification:"5767", description:"Aircrew Technician                                "
  #   Role.create classification:"3819", description:"Airfield Clearing Equipment Operating             "
  #   Role.create classification:"8882", description:"Airframe Jig Fitting                              "
  #   Role.create classification:"1854", description:"Airframe Test Operating                           "
  #   Role.create classification:"6500", description:"Alcohol Tobacco and Firearm Inspection            "
  #   Role.create classification:"5048", description:"Ammunition, Explosives, and Toxic Material Work   "
  #   Role.create classification:"0704", description:"Animal Caretaking                                 "
  #   Role.create classification:"0487", description:"Animal Health Technician                          "
  #   Role.create classification:"1171", description:"Animal Science                                    "
  #   Role.create classification:"0243", description:"Appraising                                        "
  #   Role.create classification:"0193", description:"Apprenticeship and Training                       "
  #   Role.create classification:"0808", description:"Archeology                                        "
  #   Role.create classification:"1421", description:"Architecture                                      "
  #   Role.create classification:"1420", description:"Archives Technician                               "
  #   Role.create classification:"6600", description:"Archivist                                         "
  #   Role.create classification:"1056", description:"Armament Work                                     "
  #   Role.create classification:"6605", description:"Art Specialist                                    "
  #   Role.create classification:"6606", description:"Artillery Repairing                               "
  #   Role.create classification:"3653", description:"Artillery Testing                                 "
  #   Role.create classification:"1330", description:"Asphalt Working                                   "
  #   Role.create classification:"1071", description:"Astronomy and Space Science                       "
  #   Role.create classification:"0511", description:"Audiovisual Production                            "
  #   Role.create classification:"5823", description:"Auditing                                          "
  #   Role.create classification:"0625", description:"Automotive Mechanic                               "
  #   Role.create classification:"1825", description:"Autopsy Assistant                                 "
  #   Role.create classification:"7402", description:"Aviation Safety                                   "
  #   Role.create classification:"5414", description:"Baking                                            "
  #   Role.create classification:"4445", description:"Baling Machine Operating                          "
  #   Role.create classification:"4446", description:"Bank Note Designing                               "
  #   Role.create classification:"7603", description:"Bank Note Engraving                               "
  #   Role.create classification:"7405", description:"Barbering                                         "
  #   Role.create classification:"3725", description:"Bartending                                        "
  #   Role.create classification:"4850", description:"Battery Repairing                                 "
  #   Role.create classification:"7641", description:"Bearing Reconditioning                            "
  #   Role.create classification:"4844", description:"Beautician                                        "
  #   Role.create classification:"4402", description:"Bicycle Repairing                                 "
  #   Role.create classification:"0404", description:"Bindery Working                                   "
  #   Role.create classification:"0499", description:"Biological Science Technician                     "
  #   Role.create classification:"0858", description:"Biological Student Trainee                        "
  #   Role.create classification:"3830", description:"Biomedical Engineering                            "
  #   Role.create classification:"4602", description:"Blacksmithing                                     "
  #   Role.create classification:"4717", description:"Blocking and Bracing                              "
  #   Role.create classification:"5402", description:"Boat Building and Repairing                       "
  #   Role.create classification:"3808", description:"Boiler Plant Operating                            "
  #   Role.create classification:"0011", description:"Boilermaking                                      "
  #   Role.create classification:"4441", description:"Bond Sales Promotion                              "
  #   Role.create classification:"1896", description:"Bookbinding                                       "
  #   Role.create classification:"0430", description:"Border Patrol Agent                               "
  #   Role.create classification:"4819", description:"Botany                                            "
  #   Role.create classification:"5736", description:"Bowling Equipment Repairing                       "
  #   Role.create classification:"3720", description:"Braking-Switching and Conducting                  "
  #   Role.create classification:"3940", description:"Brazing and Soldering                             "
  #   Role.create classification:"3119", description:"Broadcasting Equipment Operating                  "
  #   Role.create classification:"0560", description:"Broom and Brush Making                            "
  #   Role.create classification:"0561", description:"Budget Analysis                                   "
  #   Role.create classification:"3727", description:"Budget Clerical and Assistant                     "
  #   Role.create classification:"1176", description:"Buffing and Polishing                             "
  #   Role.create classification:"6941", description:"Building Management                               "
  #   Role.create classification:"1199", description:"Bulk Money Handling                               "
  #   Role.create classification:"2144", description:"Business and Industry Student Trainee             "
  #   Role.create classification:"4607", description:"Cargo Scheduling                                  "
  #   Role.create classification:"1371", description:"Carpentry                                         "
  #   Role.create classification:"1370", description:"Cartographic Technician                           "
  #   Role.create classification:"5435", description:"Cartography                                       "
  #   Role.create classification:"0530", description:"Carton/Bag Making Machine Operating               "
  #   Role.create classification:"3602", description:"Cash Processing                                   "
  #   Role.create classification:"1630", description:"Cement Finishing                                  "
  #   Role.create classification:"4754", description:"Cemetery Administration                           "
  #   Role.create classification:"0892", description:"Cemetery Caretaking                               "
  #   Role.create classification:"0060", description:"Ceramic Engineering                               "
  #   Role.create classification:"0893", description:"Chaplain                                          "
  #   Role.create classification:"4807", description:"Chemical Engineering                              "
  #   Role.create classification:"5427", description:"Chemical Equipment Repairing                      "
  #   Role.create classification:"1320", description:"Chemical Plant Operating                          "
  #   Role.create classification:"3736", description:"Chemistry                                         "
  #   Role.create classification:"0810", description:"Circuit Board Making                              "
  #   Role.create classification:"0160", description:"Civil Engineering                                 "
  #   Role.create classification:"0544", description:"Civil Rights Analysis                             "
  #   Role.create classification:"0998", description:"Civilian Pay                                      "
  #   Role.create classification:"0945", description:"Claims Clerical                                   "
  #   Role.create classification:"0312", description:"Clerk of Court                                    "
  #   Role.create classification:"0322", description:"Clerk-Stenographer                                "
  #   Role.create classification:"0319", description:"Clerk-Typist                                      "
  #   Role.create classification:"0062", description:"Closed Microphone Reporter                        "
  #   Role.create classification:"6903", description:"Clothing Design                                   "
  #   Role.create classification:"0357", description:"Coal Handling                                     "
  #   Role.create classification:"3513", description:"Coding                                            "
  #   Role.create classification:"3722", description:"Coin/Currency Checking                            "
  #   Role.create classification:"1144", description:"Cold Working                                      "
  #   Role.create classification:"0394", description:"Commissary Store Management                       "
  #   Role.create classification:"2508", description:"Communications Clerical                           "
  #   Role.create classification:"0020", description:"Communications Line Installing and Repairing      "
  #   Role.create classification:"0021", description:"Community Planning                                "
  #   Role.create classification:"1802", description:"Community Planning Technician                     "
  #   Role.create classification:"0335", description:"Compliance Inspection and Support                 "
  #   Role.create classification:"0854", description:"Computer Clerk and Assistant                      "
  #   Role.create classification:"0332", description:"Computer Engineering / Materials                            "
  #   Role.create classification:"1550", description:"Computer Programming / Coding                                "
  #   Role.create classification:"0334", description:"Computer Science                                 "
  #   Role.create classification:"0828", description:"Computer Design & UX                               "
  #   Role.create classification:"0809", description:"Construction Analyst                              "
  #   Role.create classification:"0696", description:"Construction Control                              "
  #   Role.create classification:"1862", description:"Consumer Safety                                   "
  #   Role.create classification:"0962", description:"Consumer Safety Inspection                        "
  #   Role.create classification:"1102", description:"Contact Representative                            "
  #   Role.create classification:"0246", description:"Contracting                                       "
  #   Role.create classification:"5450", description:"Contractor Industrial Relations                   "
  #   Role.create classification:"7404", description:"Conveyor Operating                                "
  #   Role.create classification:"1210", description:"Cooking                                           "
  #   Role.create classification:"1299", description:"Copyright                                         "
  #   Role.create classification:"1211", description:"Copyright and Patent Student Trainee              "
  #   Role.create classification:"0006", description:"Copyright Technician                              "
  #   Role.create classification:"0007", description:"Correctional Institution Administration           "
  #   Role.create classification:"0635", description:"Correctional Officer                              "
  #   Role.create classification:"0309", description:"Corrective Therapist                              "
  #   Role.create classification:"5484", description:"Correspondence Clerk                              "
  #   Role.create classification:"5725", description:"Counting Machine Operating                        "
  #   Role.create classification:"1811", description:"Crane Operating                                   "
  #   Role.create classification:"1161", description:"Criminal Investigating                            "
  #   Role.create classification:"1162", description:"Crop Insurance Administration                     "
  #   Role.create classification:"1541", description:"Crop Insurance Underwriting                       "
  #   Role.create classification:"1540", description:"Cryptanalysis                                     "
  #   Role.create classification:"4808", description:"Cryptography                                      "
  #   Role.create classification:"3566", description:"Custodial Equipment Servicing                     "
  #   Role.create classification:"1897", description:"Custodial Working                                 "
  #   Role.create classification:"1894", description:"Customs Aid                                       "
  #   Role.create classification:"1890", description:"Customs Entry and Liquidation                     "
  #   Role.create classification:"1884", description:"Customs Inspection                                "
  #   Role.create classification:"1895", description:"Customs Patrol Officer                            "
  #   Role.create classification:"5034", description:"Customs Warehouse Officer                         "
  #   Role.create classification:"0356", description:"Dairy Farming                                     "
  #   Role.create classification:"5788", description:"Data Transcriber                                  "
  #   Role.create classification:"0681", description:"Deckhand                                          "
  #   Role.create classification:"0682", description:"Dental Assistant                                  "
  #   Role.create classification:"0683", description:"Dental Hygiene                                    "
  #   Role.create classification:"0680", description:"Dental Lab Aid and Technician                     "
  #   Role.create classification:"0995", description:"Dental Officer                                    "
  #   Role.create classification:"1226", description:"Dependents and Estates Claims Examiner            "
  #   Role.create classification:"0647", description:"Design Patent Examining                           "
  #   Role.create classification:"3428", description:"Diagnostic Radiology Technician                   "
  #   Role.create classification:"0630", description:"Die Sinking                                       "
  #   Role.create classification:"2151", description:"Dietitian and Nutritionist                        "
  #   Role.create classification:"2030", description:"Dispatching                                       "
  #   Role.create classification:"1397", description:"Distribution Facility and Store Management        "
  #   Role.create classification:"4855", description:"Document Analysis                                 "
  #   Role.create classification:"5364", description:"Domestic Appliance Repairing                      "
  #   Role.create classification:"5430", description:"Door Systems Mechanic                             "
  #   Role.create classification:"5479", description:"Drawbridge Operating                              "
  #   Role.create classification:"5729", description:"Dredging Equipment Operating                      "
  #   Role.create classification:"7307", description:"Drill Rig Operating                               "
  #   Role.create classification:"0408", description:"Dry Cleaning                                      "
  #   Role.create classification:"0119", description:"Ecology                                           "
  #   Role.create classification:"0110", description:"Economics Assistant                               "
  #   Role.create classification:"1087", description:"Economist                                         "
  #   Role.create classification:"1702", description:"Editorial Assistant                               "
  #   Role.create classification:"1710", description:"Education and Training Technician                 "
  #   Role.create classification:"1720", description:"Education and Vocational Training                 "
  #   Role.create classification:"1730", description:"Education Program                                 "
  #   Role.create classification:"1740", description:"Education Research                                "
  #   Role.create classification:"1799", description:"Education Services                                "
  #   Role.create classification:"0639", description:"Education Student Trainee                         "
  #   Role.create classification:"5407", description:"Educational Therapist                             "
  #   Role.create classification:"0850", description:"Electric Power Controlling                        "
  #   Role.create classification:"2854", description:"Electrical Engineering                            "
  #   Role.create classification:"2800", description:"Electrical Equipment Repairing                    "
  #   Role.create classification:"2805", description:"Electrical Installation and Maintenance           "
  #   Role.create classification:"2810", description:"Electrician                                       "
  #   Role.create classification:"4449", description:"Electrician (High Voltage)                        "
  #   Role.create classification:"5876", description:"Electrolytic Intaglio Platemaking                 "
  #   Role.create classification:"0359", description:"Electromotive Equipment Mechanic                  "
  #   Role.create classification:"0362", description:"Electronic Accounting Machine Operator            "
  #   Role.create classification:"2608", description:"Electronic Accounting Machine Program Planning    "
  #   Role.create classification:"2600", description:"Electronic Digital Computer Mechanic              "
  #   Role.create classification:"2606", description:"Electronic Equipment Installation and Maintenance "
  #   Role.create classification:"2610", description:"Electronic Industrial Controls Mechanic           "
  #   Role.create classification:"2602", description:"Electronic Integrated Systems Mechanic            "
  #   Role.create classification:"2604", description:"Electronics Engineering                           "
  #   Role.create classification:"0856", description:"Electronics Mechanic                              "
  #   Role.create classification:"3711", description:"Electronics Technician                            "
  #   Role.create classification:"5313", description:"Electroplating                                    "
  #   Role.create classification:"5438", description:"Elevator Mechanic                                 "
  #   Role.create classification:"0235", description:"Elevator Operating                                "
  #   Role.create classification:"0230", description:"Employee Development                              "
  #   Role.create classification:"8600", description:"Employee Relations                                "
  #   Role.create classification:"0899", description:"Engine Overhaul                                   "
  #   Role.create classification:"0818", description:"Engineering and Architecture Student Trainee      "
  #   Role.create classification:"5716", description:"Engineering Drafting                              "
  #   Role.create classification:"0802", description:"Engineering Equipment Operating                   "
  #   Role.create classification:"3816", description:"Engineering Technician                            "
  #   Role.create classification:"0414", description:"Engraving                                         "
  #   Role.create classification:"0819", description:"Entomology                                        "
  #   Role.create classification:"0698", description:"Environmental Engineering                         "
  #   Role.create classification:"0029", description:"Environmental Health Technician                   "
  #   Role.create classification:"0028", description:"Environmental Protection Assistant                "
  #   Role.create classification:"0361", description:"Equal Employment Opportunity                      "
  #   Role.create classification:"7009", description:"Equipment and Facility Management Student Trainee "
  #   Role.create classification:"0350", description:"Equipment Cleaning                                "
  #   Role.create classification:"1670", description:"Equipment Operator                                "
  #   Role.create classification:"0920", description:"Equipment Specialist                              "
  #   Role.create classification:"4715", description:"Estate Tax Planning                               "
  #   Role.create classification:"1010", description:"Exhibits Making/Modeling                          "
  #   Role.create classification:"6502", description:"Exhibits Specialist                               "
  #   Role.create classification:"6517", description:"Explosives Operating                              "
  #   Role.create classification:"3100", description:"Explosives Test Operating                         "
  #   Role.create classification:"3105", description:"Fabric and Leather Work                           "
  #   Role.create classification:"1640", description:"Fabric Working                                    "
  #   Role.create classification:"5002", description:"Facility Management                               "
  #   Role.create classification:"0270", description:"Farming                                           "
  #   Role.create classification:"9000", description:"Federal Retirement Benefits                       "
  #   Role.create classification:"9003", description:"File Processing                                   "
  #   Role.create classification:"4405", description:"Film Assembling and Repairing                     "
  #   Role.create classification:"4839", description:"Film Assembly-Stripping                           "
  #   Role.create classification:"0501", description:"Film Processing Equipment Repairing               "
  #   Role.create classification:"1160", description:"Financial Administration and Program              "
  #   Role.create classification:"0503", description:"Financial Analysis                                "
  #   Role.create classification:"0570", description:"Financial Clerk and Assistant                     "
  #   Role.create classification:"0505", description:"Financial Institution Examination                 "
  #   Role.create classification:"0599", description:"Financial Management                              "
  #   Role.create classification:"0072", description:"Financial Management Student Trainee              "
  #   Role.create classification:"0081", description:"Fingerprint Identification                        "
  #   Role.create classification:"0804", description:"Fire Protection and Prevention                    "
  #   Role.create classification:"0482", description:"Fire Protection Engineer                          "
  #   Role.create classification:"3702", description:"Fishery Biology                                   "
  #   Role.create classification:"3609", description:"Flame/Arc Cutting                                 "
  #   Role.create classification:"8200", description:"Floor Covering Installing                         "
  #   Role.create classification:"0120", description:"Fluid Systems Maintenance                         "
  #   Role.create classification:"1863", description:"Food Assistance Program Specialist                "
  #   Role.create classification:"7400", description:"Food Inspection                                   "
  #   Role.create classification:"7408", description:"Food Preparation and Serving                      "
  #   Role.create classification:"1382", description:"Food Service Working                              "
  #   Role.create classification:"5444", description:"Food Technology                                   "
  #   Role.create classification:"0130", description:"Food/Feed Processing Equipment Operating          "
  #   Role.create classification:"0135", description:"Foreign Affairs                                   "
  #   Role.create classification:"0095", description:"Foreign Agricultural Affairs                      "
  #   Role.create classification:"1380", description:"Foreign Law Specialist                            "
  #   Role.create classification:"0460", description:"Forest Products Technology                        "
  #   Role.create classification:"0462", description:"Forestry                                          "
  #   Role.create classification:"5704", description:"Forestry Technician                               "
  #   Role.create classification:"4654", description:"Fork Lift Operating                               "
  #   Role.create classification:"2131", description:"Form Block Making                                 "
  #   Role.create classification:"5413", description:"Freight Rate                                      "
  #   Role.create classification:"4255", description:"Fuel Distribution System Operating                "
  #   Role.create classification:"0050", description:"Fuel Distribution Systems Mechanic                "
  #   Role.create classification:"3741", description:"Funeral Directing                                 "
  #   Role.create classification:"1812", description:"Furnace Operating                                 "
  #   Role.create classification:"5003", description:"Game Law Enforcement                              "
  #   Role.create classification:"5205", description:"Gardening                                         "
  #   Role.create classification:"5433", description:"Gas and Radiation Detecting                       "
  #   Role.create classification:"5384", description:"Gas Generating Plan Operating                     "
  #   Role.create classification:"0190", description:"Gasdynamic Facility Installing and Repairing      "
  #   Role.create classification:"1001", description:"General Anthropology                              "
  #   Role.create classification:"0905", description:"General Arts and Information                      "
  #   Role.create classification:"0401", description:"General Attorney                                  "
  #   Role.create classification:"1101", description:"General Biological Science                        "
  #   Role.create classification:"0990", description:"General Business and Industry                     "
  #   Role.create classification:"1701", description:"General Claims Examining                          "
  #   Role.create classification:"0801", description:"General Education and Training                    "
  #   Role.create classification:"4800", description:"General Engineering                               "
  #   Role.create classification:"4737", description:"General Equipment Maintenance                     "
  #   Role.create classification:"4741", description:"General Equipment Mechanic                        "
  #   Role.create classification:"1601", description:"General Equipment Operating                       "
  #   Role.create classification:"0480", description:"General Facilities and Equipment                  "
  #   Role.create classification:"0601", description:"General Fish and Wildlife Administration          "
  #   Role.create classification:"1801", description:"General Health Science                            "
  #   Role.create classification:"1810", description:"General Inspection, Investigation, and Compliance "
  #   Role.create classification:"4700", description:"General Investigating                             "
  #   Role.create classification:"1301", description:"General Maintenance and Operations Work           "
  #   Role.create classification:"3500", description:"General Physical Science                          "
  #   Role.create classification:"0099", description:"General Services and Support Work                 "
  #   Role.create classification:"2001", description:"General Student Trainee                           "
  #   Role.create classification:"0392", description:"General Supply                                    "
  #   Role.create classification:"0440", description:"General Telecommunications                        "
  #   Role.create classification:"1372", description:"Genetics                                          "
  #   Role.create classification:"1374", description:"Geodesy                                           "
  #   Role.create classification:"0150", description:"Geodetic Technician                               "
  #   Role.create classification:"1350", description:"Geography                                         "
  #   Role.create classification:"1313", description:"Geology                                           "
  #   Role.create classification:"4370", description:"Geophysics                                        "
  #   Role.create classification:"3611", description:"Glassblowing                                      "
  #   Role.create classification:"0090", description:"Glazing                                           "
  #   Role.create classification:"4403", description:"Guide                                             "
  #   Role.create classification:"0640", description:"Hand Composing                                    "
  #   Role.create classification:"0107", description:"Health Aid and Technician                         "
  #   Role.create classification:"1306", description:"Health Insurance Administration                   "
  #   Role.create classification:"0670", description:"Health Physics                                    "
  #   Role.create classification:"0671", description:"Health System Administration                      "
  #   Role.create classification:"0930", description:"Health System Specialist                          "
  #   Role.create classification:"3712", description:"Hearing and Appeals                               "
  #   Role.create classification:"5309", description:"Heat Treating                                     "
  #   Role.create classification:"5803", description:"Heating and Boiler Plant Equipment                "
  #   Role.create classification:"2125", description:"Heavy Mobile Equipment Mechanic                   "
  #   Role.create classification:"0170", description:"Highway Safety                                    "
  #   Role.create classification:"0493", description:"History                                           "
  #   Role.create classification:"0437", description:"Home Economics                                    "
  #   Role.create classification:"0673", description:"Horticulture                                      "
  #   Role.create classification:"1173", description:"Hospital Housekeeping Management                  "
  #   Role.create classification:"1316", description:"Housing Management                                "
  #   Role.create classification:"1315", description:"Hydrologic Technician                             "
  #   Role.create classification:"1020", description:"Hydrology                                         "
  #   Role.create classification:"1816", description:"Illustrating                                      "
  #   Role.create classification:"1889", description:"Immigration Inspection                            "
  #   Role.create classification:"5403", description:"Import Specialist                                 "
  #   Role.create classification:"0896", description:"Incinerator Operating                             "
  #   Role.create classification:"0895", description:"Industrial Engineering                            "
  #   Role.create classification:"5300", description:"Industrial Engineering Technician                 "
  #   Role.create classification:"5352", description:"Industrial Equipment Maintenance                  "
  #   Role.create classification:"5400", description:"Industrial Equipment Mechanic                     "
  #   Role.create classification:"5341", description:"Industrial Equipment Operating                    "
  #   Role.create classification:"0690", description:"Industrial Furnace Building and Repairing         "
  #   Role.create classification:"1103", description:"Industrial Hygiene                                "
  #   Role.create classification:"1150", description:"Industrial Property Management                    "
  #   Role.create classification:"1099", description:"Industrial Specialist                             "
  #   Role.create classification:"0304", description:"Information and Arts Student Trainee              "
  #   Role.create classification:"5031", description:"Information Receptionist                          "
  #   Role.create classification:"1750", description:"Insects Production Working                        "
  #   Role.create classification:"4157", description:"Instructional Systems                             "
  #   Role.create classification:"3314", description:"Instrument Dial Painting                          "
  #   Role.create classification:"3359", description:"Instrument Making                                 "
  #   Role.create classification:"3300", description:"Instrument Mechanic                               "
  #   Role.create classification:"3610", description:"Instrument Work                                   "
  #   Role.create classification:"0593", description:"Insulating                                        "
  #   Role.create classification:"1163", description:"Insurance Accounts                                "
  #   Role.create classification:"4450", description:"Insurance Examining                               "
  #   Role.create classification:"4454", description:"Intaglio Die and Plate Finishing                  "
  #   Role.create classification:"0132", description:"Intaglio Press Operating                          "
  #   Role.create classification:"0134", description:"Intelligence                                      "
  #   Role.create classification:"1008", description:"Intelligence Aid and Clerk                        "
  #   Role.create classification:"0512", description:"Interior Design                                   "
  #   Role.create classification:"1169", description:"Internal Revenue Agent                            "
  #   Role.create classification:"0136", description:"Internal Revenue Officer                          "
  #   Role.create classification:"0131", description:"International Cooperation                         "
  #   Role.create classification:"2010", description:"International Relations                           "
  #   Role.create classification:"1899", description:"Inventory Management                              "
  #   Role.create classification:"0459", description:"Investigation Student Trainee                     "
  #   Role.create classification:"5310", description:"Irrigation System Operator                        "
  #   Role.create classification:"0244", description:"Kitchen/Bakery Equipment Repairing                "
  #   Role.create classification:"0233", description:"Labor Management Relations Exam                   "
  #   Role.create classification:"3515", description:"Labor Relations                                   "
  #   Role.create classification:"3511", description:"Laboratory Support                                "
  #   Role.create classification:"3502", description:"Laboratory Working                                "
  #   Role.create classification:"0965", description:"Laboring                                          "
  #   Role.create classification:"1373", description:"Land Law Examining                                "
  #   Role.create classification:"0807", description:"Land Surveying                                    "
  #   Role.create classification:"1046", description:"Landscape Architecture                            "
  #   Role.create classification:"1040", description:"Language Clerical                                 "
  #   Role.create classification:"5317", description:"Language Specialist                               "
  #   Role.create classification:"7305", description:"Laundry and Dry Cleaning Equipment Repairing      "
  #   Role.create classification:"7304", description:"Laundry Machine Operating                         "
  #   Role.create classification:"7300", description:"Laundry Working                                   "
  #   Role.create classification:"1658", description:"Laundry, Dry Cleaning, and Pressing               "
  #   Role.create classification:"0904", description:"Laundry/Drycleaning Plant Management              "
  #   Role.create classification:"3716", description:"Law Clerk                                         "
  #   Role.create classification:"0986", description:"Leadburning                                       "
  #   Role.create classification:"0963", description:"Legal Clerical and Assistant                      "
  #   Role.create classification:"0999", description:"Legal Instruments Examiner                        "
  #   Role.create classification:"4000", description:"Legal Occupation Student Trainee                  "
  #   Role.create classification:"4406", description:"Lens and Crystal Work                             "
  #   Role.create classification:"1410", description:"Letterpress Operating                             "
  #   Role.create classification:"1499", description:"Librarian                                         "
  #   Role.create classification:"1411", description:"Library and Archives Student Trainee              "
  #   Role.create classification:"8675", description:"Library Technician                                "
  #   Role.create classification:"5035", description:"Liquid Fuel Rocket Engine Mechanic                "
  #   Role.create classification:"1165", description:"Livestock Ranching/Wrangling                      "
  #   Role.create classification:"5426", description:"Loan Specialist                                   "
  #   Role.create classification:"5318", description:"Lock and Dam Operating                            "
  #   Role.create classification:"4804", description:"Lock and Dam Repairing                            "
  #   Role.create classification:"5737", description:"Locksmithing                                      "
  #   Role.create classification:"5221", description:"Locomotive Engineering                            "
  #   Role.create classification:"0346", description:"Lofting                                           "
  #   Role.create classification:"0992", description:"Logistics Management                              "
  #   Role.create classification:"6902", description:"Loss and Damage Claims Examiner                   "
  #   Role.create classification:"3431", description:"Lumber Handling                                   "
  #   Role.create classification:"3400", description:"Machine Tool Operating                            "
  #   Role.create classification:"3414", description:"Machine Tool Work                                 "
  #   Role.create classification:"0305", description:"Machining                                         "
  #   Role.create classification:"4749", description:"Mail and File Clerk                               "
  #   Role.create classification:"0343", description:"Maintenance Mechanic                              "
  #   Role.create classification:"0344", description:"Management and Program Analysis                   "
  #   Role.create classification:"0142", description:"Management and Program Clerk Assistant            "
  #   Role.create classification:"0140", description:"Manpower Development                              "
  #   Role.create classification:"0637", description:"Manpower Research and Analysis                    "
  #   Role.create classification:"2161", description:"Manual Arts Therapist                             "
  #   Role.create classification:"5334", description:"Marine Cargo                                      "
  #   Role.create classification:"3603", description:"Marine Machinery Mechanic                         "
  #   Role.create classification:"0806", description:"Masonry                                           "
  #   Role.create classification:"6912", description:"Materials Engineering                             "
  #   Role.create classification:"6910", description:"Materials Examining and Identifying               "
  #   Role.create classification:"6907", description:"Materials Expediting                              "
  #   Role.create classification:"1529", description:"Materials Handler                                 "
  #   Role.create classification:"1520", description:"Mathematical Statistician                         "
  #   Role.create classification:"1599", description:"Mathematics                                       "
  #   Role.create classification:"1521", description:"Mathematics and Statistics Student Trainee        "
  #   Role.create classification:"7407", description:"Mathematics Technician                            "
  #   Role.create classification:"0830", description:"Meatcutting                                       "
  #   Role.create classification:"4848", description:"Mechanical Engineering                            "
  #   Role.create classification:"3832", description:"Mechanical Parts Repairing                        "
  #   Role.create classification:"0241", description:"Medal Making                                      "
  #   Role.create classification:"0679", description:"Mediation                                         "
  #   Role.create classification:"4805", description:"Medical Clerk                                     "
  #   Role.create classification:"0699", description:"Medical Equipment Repairing                       "
  #   Role.create classification:"0649", description:"Medical Health Student Trainee                    "
  #   Role.create classification:"0602", description:"Medical Instrument Technician                     "
  #   Role.create classification:"0669", description:"Medical Officer                                   "
  #   Role.create classification:"0675", description:"Medical Records Administration                    "
  #   Role.create classification:"0622", description:"Medical Records Technician                        "
  #   Role.create classification:"0645", description:"Medical Supply Aid and Technician                 "
  #   Role.create classification:"0650", description:"Medical Technician                                "
  #   Role.create classification:"0644", description:"Medical Technician Assistant                      "
  #   Role.create classification:"0302", description:"Medical Technologist                              "
  #   Role.create classification:"3802", description:"Messenger                                         "
  #   Role.create classification:"3869", description:"Metal Forging                                     "
  #   Role.create classification:"3735", description:"Metal Forming Machine Operating                   "
  #   Role.create classification:"3708", description:"Metal Phototransferring                           "
  #   Role.create classification:"3700", description:"Metal Processing                                  "
  #   Role.create classification:"3858", description:"Metal Processing                                  "
  #   Role.create classification:"3872", description:"Metal Tank and Radiator Repairing                 "
  #   Role.create classification:"3800", description:"Metal Tube Making, Installing, and Repairing      "
  #   Role.create classification:"3707", description:"Metal Work                                        "
  #   Role.create classification:"1321", description:"Metalizing                                        "
  #   Role.create classification:"1341", description:"Metallurgy                                        "
  #   Role.create classification:"1340", description:"Meteorological Technician                         "
  #   Role.create classification:"0403", description:"Meteorology                                       "
  #   Role.create classification:"0545", description:"Microbiology                                      "
  #   Role.create classification:"0204", description:"Military Pay                                      "
  #   Role.create classification:"0205", description:"Military Personnel Clerk and Technician           "
  #   Role.create classification:"1822", description:"Military Personnel Management                     "
  #   Role.create classification:"0880", description:"Mine Safety and Health                            "
  #   Role.create classification:"0301", description:"Mining Engineering                                "
  #   Role.create classification:"0303", description:"Miscellaneous Administration and Program          "
  #   Role.create classification:"5200", description:"Miscellaneous Clerk                               "
  #   Role.create classification:"6511", description:"Miscellaneous Occupations                         "
  #   Role.create classification:"3809", description:"Missile/Toxic Materials Handling                  "
  #   Role.create classification:"5806", description:"Mobile Equipment Metal Mechanic                   "
  #   Role.create classification:"4714", description:"Mobile Equipment Servicing                        "
  #   Role.create classification:"4373", description:"Model Making                                      "
  #   Role.create classification:"9004", description:"Molding                                           "
  #   Role.create classification:"3910", description:"Motion Picture Developing/Printing Machine Operati"
  #   Role.create classification:"3900", description:"Motion Picture Projection                         "
  #   Role.create classification:"2123", description:"Motion Picture, Radio, Television, and Sound Equip"
  #   Role.create classification:"5703", description:"Motor Carrier Safety                              "
  #   Role.create classification:"6505", description:"Motor Vehicle Operating                           "
  #   Role.create classification:"1015", description:"Munitions Destroying                              "
  #   Role.create classification:"1016", description:"Museum Curator                                    "
  #   Role.create classification:"1051", description:"Museum Specialist                                 "
  #   Role.create classification:"0871", description:"Music Specialist                                  "
  #   Role.create classification:"4843", description:"Naval Architecture                                "
  #   Role.create classification:"1361", description:"Navigation Aids Repairing                         "
  #   Role.create classification:"4413", description:"Navigational Information                          "
  #   Role.create classification:"3705", description:"Negative Engraving                                "
  #   Role.create classification:"0840", description:"Nondestructive Testing                            "
  #   Role.create classification:"0084", description:"Nuclear Engineering                               "
  #   Role.create classification:"0642", description:"Nuclear Material Courier                          "
  #   Role.create classification:"0610", description:"Nuclear Medicine Technician                       "
  #   Role.create classification:"0621", description:"Nurse                                             "
  #   Role.create classification:"0222", description:"Nursing Assistant                                 "
  #   Role.create classification:"0631", description:"Occupational Analysis                             "
  #   Role.create classification:"1360", description:"Occupational Therapist                            "
  #   Role.create classification:"4806", description:"Oceanography                                      "
  #   Role.create classification:"0326", description:"Office Appliance Repairing                        "
  #   Role.create classification:"1021", description:"Office Automation Clerk                           "
  #   Role.create classification:"4414", description:"Office Drafting                                   "
  #   Role.create classification:"4417", description:"Offset Photography                                "
  #   Role.create classification:"5323", description:"Offset Press Operating                            "
  #   Role.create classification:"1515", description:"Oiling and Greasing                               "
  #   Role.create classification:"4005", description:"Operations Research                               "
  #   Role.create classification:"3306", description:"Optical Element Working                           "
  #   Role.create classification:"0662", description:"Optical Instrument Repairing                      "
  #   Role.create classification:"6641", description:"Optometrist                                       "
  #   Role.create classification:"4845", description:"Ordnance Equipment Mechanic                       "
  #   Role.create classification:"0667", description:"Orthopedic Appliance Repairing                    "
  #   Role.create classification:"0023", description:"Orthotist and Prosthetist                         "
  #   Role.create classification:"2032", description:"Outdoor Recreation Planning                       "
  #   Role.create classification:"5440", description:"Packaging                                         "
  #   Role.create classification:"7002", description:"Packaging Machine Operating                       "
  #   Role.create classification:"7000", description:"Packing                                           "
  #   Role.create classification:"4102", description:"Packing and Processing                            "
  #   Role.create classification:"4100", description:"Painting                                          "
  #   Role.create classification:"5455", description:"Painting and Paper                                "
  #   Role.create classification:"4103", description:"Paper Pulping Machine Operating                   "
  #   Role.create classification:"7010", description:"Paperhanging                                      "
  #   Role.create classification:"0950", description:"Parachute Packing                                 "
  #   Role.create classification:"0025", description:"Paralegal Specialist                              "
  #   Role.create classification:"0967", description:"Park Ranger                                       "
  #   Role.create classification:"1220", description:"Passport and Visa Examining                       "
  #   Role.create classification:"1221", description:"Patent Administration                             "
  #   Role.create classification:"1222", description:"Patent Advisor                                    "
  #   Role.create classification:"1223", description:"Patent Attorney                                   "
  #   Role.create classification:"1224", description:"Patent Classifying                                "
  #   Role.create classification:"1202", description:"Patent Examining                                  "
  #   Role.create classification:"0646", description:"Patent Technician                                 "
  #   Role.create classification:"4616", description:"Pathology Technician                              "
  #   Role.create classification:"0958", description:"Patternmaking                                     "
  #   Role.create classification:"7600", description:"Pension Law Specialist                            "
  #   Role.create classification:"0203", description:"Personal Services                                 "
  #   Role.create classification:"0201", description:"Personnel Clerk and Assistant                     "
  #   Role.create classification:"0299", description:"Personnel Management                              "
  #   Role.create classification:"0212", description:"Personnel Management Student Trainee              "
  #   Role.create classification:"5026", description:"Personnel Staffing                                "
  #   Role.create classification:"0881", description:"Pest Controlling                                  "
  #   Role.create classification:"0660", description:"Petroleum Engineering                             "
  #   Role.create classification:"0405", description:"Pharmacist                                        "
  #   Role.create classification:"0661", description:"Pharmacology                                      "
  #   Role.create classification:"4425", description:"Pharmacy Technician                               "
  #   Role.create classification:"1386", description:"Photoengraving                                    "
  #   Role.create classification:"1060", description:"Photographic Technology                           "
  #   Role.create classification:"1399", description:"Photography                                       "
  #   Role.create classification:"1311", description:"Physical Science Student Trainee                  "
  #   Role.create classification:"0633", description:"Physical Science Technician                       "
  #   Role.create classification:"0603", description:"Physical Therapist                                "
  #   Role.create classification:"1310", description:"Physician's Assistant                             "
  #   Role.create classification:"5365", description:"Physics                                           "
  #   Role.create classification:"0413", description:"Physiological Trainer Mechanic                    "
  #   Role.create classification:"4204", description:"Physiology                                        "
  #   Role.create classification:"3508", description:"Pipefitting                                       "
  #   Role.create classification:"5000", description:"Pipeline Working                                  "
  #   Role.create classification:"0434", description:"Plant and Animal Work                             "
  #   Role.create classification:"0435", description:"Plant Pathology                                   "
  #   Role.create classification:"0436", description:"Plant Physiology                                  "
  #   Role.create classification:"0421", description:"Plant Protection and Quarantine                   "
  #   Role.create classification:"4371", description:"Plant Protection Technician                       "
  #   Role.create classification:"3605", description:"Plaster Pattern Casting                           "
  #   Role.create classification:"4352", description:"Plastering                                        "
  #   Role.create classification:"4351", description:"Plastic Fabricating                               "
  #   Role.create classification:"4416", description:"Plastic Molding Equipment Operating               "
  #   Role.create classification:"4300", description:"Platemaking                                       "
  #   Role.create classification:"4206", description:"Pliable Materials Work                            "
  #   Role.create classification:"4200", description:"Plumbing                                          "
  #   Role.create classification:"8255", description:"Plumbing and Pipefitting                          "
  #   Role.create classification:"3815", description:"Pneudraulic Systems Mechanic                      "
  #   Role.create classification:"0668", description:"Pneumatic Tool Operating                          "
  #   Role.create classification:"0083", description:"Podiatrist                                        "
  #   Role.create classification:"5478", description:"Police                                            "
  #   Role.create classification:"0221", description:"Portable Equipment Operating                      "
  #   Role.create classification:"3422", description:"Position Classification                           "
  #   Role.create classification:"5378", description:"Power Saw Operating                               "
  #   Role.create classification:"0620", description:"Powered Support Systems Mechanic                  "
  #   Role.create classification:"4010", description:"Practical Nurse                                   "
  #   Role.create classification:"7004", description:"Prescription Eyeglass Making                      "
  #   Role.create classification:"7006", description:"Preservation Packaging                            "
  #   Role.create classification:"7306", description:"Preservation Servicing                            "
  #   Role.create classification:"4400", description:"Pressing                                          "
  #   Role.create classification:"0351", description:"Printing                                          "
  #   Role.create classification:"5330", description:"Printing Clerical                                 "
  #   Role.create classification:"1654", description:"Printing Equipment Repairing                      "
  #   Role.create classification:"1106", description:"Printing Management                               "
  #   Role.create classification:"1152", description:"Procurement Clerk and Technician                  "
  #   Role.create classification:"5350", description:"Production Control                                "
  #   Role.create classification:"0340", description:"Production Machinery Mechanic                     "
  #   Role.create classification:"3364", description:"Program Management                                "
  #   Role.create classification:"1104", description:"Projection Equipment Repairing                    "
  #   Role.create classification:"1107", description:"Property Disposal                                 "
  #   Role.create classification:"0672", description:"Property Disposal Clerk and Technician            "
  #   Role.create classification:"4816", description:"Prosthetic Representative                         "
  #   Role.create classification:"0180", description:"Protective and Safety Fabricating and Repairing   "
  #   Role.create classification:"0181", description:"Psychology                                        "
  #   Role.create classification:"3941", description:"Psychology Aid and Technician                     "
  #   Role.create classification:"1035", description:"Public Address Equipment Operating                "
  #   Role.create classification:"1725", description:"Public Affairs                                    "
  #   Role.create classification:"0685", description:"Public Health Education                           "
  #   Role.create classification:"1864", description:"Public Health Program Specialist                  "
  #   Role.create classification:"1130", description:"Public Health Quarantine Inspection               "
  #   Role.create classification:"1105", description:"Public Utilities Specialist                       "
  #   Role.create classification:"1910", description:"Purchasing                                        "
  #   Role.create classification:"1999", description:"Quality Assurance                                 "
  #   Role.create classification:"4716", description:"Quality Inspection Student Trainee                "
  #   Role.create classification:"5738", description:"Railroad Car Repairing                            "
  #   Role.create classification:"3546", description:"Railroad Maintenance Vehicle Operating            "
  #   Role.create classification:"2121", description:"Railroad Repairing                                "
  #   Role.create classification:"0455", description:"Railroad Safety                                   "
  #   Role.create classification:"0454", description:"Range Technician                                  "
  #   Role.create classification:"1170", description:"Rangeland Management                              "
  #   Role.create classification:"0638", description:"Realty                                            "
  #   Role.create classification:"4851", description:"Rec/Creative Arts Therapist                       "
  #   Role.create classification:"0189", description:"Reclamation Working                               "
  #   Role.create classification:"0188", description:"Recreation Aid and Assistant                      "
  #   Role.create classification:"0636", description:"Recreation Specialist                             "
  #   Role.create classification:"4745", description:"Rehabilitation Therapy Assistant                  "
  #   Role.create classification:"0651", description:"Research Laboratory Mechanic                      "
  #   Role.create classification:"0664", description:"Respiratory Therapist                             "
  #   Role.create classification:"5210", description:"Restoration Technician                            "
  #   Role.create classification:"5784", description:"Rigging                                           "
  #   Role.create classification:"5706", description:"Riverboat Operating                               "
  #   Role.create classification:"3606", description:"Road Sweeper Operating                            "
  #   Role.create classification:"4361", description:"Roofing                                           "
  #   Role.create classification:"4360", description:"Rubber Equipment Repairing                        "
  #   Role.create classification:"0018", description:"Rubber Products Molding                           "
  #   Role.create classification:"0803", description:"Safety and Occupational Health Management         "
  #   Role.create classification:"0019", description:"Safety Engineering                                "
  #   Role.create classification:"0223", description:"Safety Technician                                 "
  #   Role.create classification:"2091", description:"Salary and Wage Administration                    "
  #   Role.create classification:"5423", description:"Sales Store Clerical                              "
  #   Role.create classification:"0688", description:"Sandblasting                                      "
  #   Role.create classification:"4812", description:"Sanitarian                                        "
  #   Role.create classification:"4447", description:"Saw Reconditioning                                "
  #   Role.create classification:"0318", description:"Sculptural Engraving                              "
  #   Role.create classification:"1831", description:"Secretary                                         "
  #   Role.create classification:"0080", description:"Securities Compliance Examining                   "
  #   Role.create classification:"0086", description:"Security Administration                           "
  #   Role.create classification:"0085", description:"Security Clerical and Assistant                   "
  #   Role.create classification:"3111", description:"Security Guard                                    "
  #   Role.create classification:"5312", description:"Sewing Machine Operating                          "
  #   Role.create classification:"3806", description:"Sewing Machine Repairing                          "
  #   Role.create classification:"5782", description:"Sheet Metal Mechanic                              "
  #   Role.create classification:"0873", description:"Ship Operating                                    "
  #   Role.create classification:"3820", description:"Ship Surveying                                    "
  #   Role.create classification:"5220", description:"Shipfitting                                       "
  #   Role.create classification:"3103", description:"Shipwright                                        "
  #   Role.create classification:"3769", description:"Shoe Repairing                                    "
  #   Role.create classification:"4448", description:"Shot Peening Machine Operating                    "
  #   Role.create classification:"4104", description:"Siderographic Transferring                        "
  #   Role.create classification:"4419", description:"Sign Painting                                     "
  #   Role.create classification:"6610", description:"Silk Screen Making and Printing                   "
  #   Role.create classification:"5786", description:"Small Arms Repairing                              "
  #   Role.create classification:"8610", description:"Small Craft Operating                             "
  #   Role.create classification:"0105", description:"Small Engine Mechanic                             "
  #   Role.create classification:"0993", description:"Social Insurance Administration                   "
  #   Role.create classification:"0101", description:"Social Insurance Claims Examining                 "
  #   Role.create classification:"0102", description:"Social Science                                    "
  #   Role.create classification:"0199", description:"Social Science Aid and Technician                 "
  #   Role.create classification:"0186", description:"Social Science Student Trainee                    "
  #   Role.create classification:"0187", description:"Social Service Aid and Assistant                  "
  #   Role.create classification:"0185", description:"Social Services                                   "
  #   Role.create classification:"0184", description:"Social Work                                       "
  #   Role.create classification:"0457", description:"Sociology                                         "
  #   Role.create classification:"0458", description:"Soil Conservation                                 "
  #   Role.create classification:"0470", description:"Soil Conservation Technician                      "
  #   Role.create classification:"5454", description:"Soil Science                                      "
  #   Role.create classification:"3911", description:"Solvent Still Operating                           "
  #   Role.create classification:"6656", description:"Sound Recording Equipment Operating               "
  #   Role.create classification:"0665", description:"Special Weapons Systems Mechanic                  "
  #   Role.create classification:"0030", description:"Speech Pathology Audiology                        "
  #   Role.create classification:"3818", description:"Sports Specialist                                 "
  #   Role.create classification:"5419", description:"Springmaking                                      "
  #   Role.create classification:"1531", description:"Stationary-Engine Operating                       "
  #   Role.create classification:"1530", description:"Statistical Assistant                             "
  #   Role.create classification:"4440", description:"Statistician                                      "
  #   Role.create classification:"3543", description:"Stereotype Platemaking                            "
  #   Role.create classification:"1667", description:"Stevedoring                                       "
  #   Role.create classification:"6914", description:"Steward                                           "
  #   Role.create classification:"3600", description:"Store Working                                     "
  #   Role.create classification:"3807", description:"Structural and Finishing Work                     "
  #   Role.create classification:"2050", description:"Structural/Ornamental Iron Working                "
  #   Role.create classification:"2005", description:"Supply Cataloging                                 "
  #   Role.create classification:"2003", description:"Supply Clerical and Technician                    "
  #   Role.create classification:"2099", description:"Supply Program Management                         "
  #   Role.create classification:"0342", description:"Supply Student Trainee                            "
  #   Role.create classification:"0817", description:"Support Services Administration                   "
  #   Role.create classification:"5486", description:"Surveying Technician                              "
  #   Role.create classification:"5707", description:"Swimming Pool Operating                           "
  #   Role.create classification:"0592", description:"Tank Operating                                    "
  #   Role.create classification:"0987", description:"Tax Examining                                     "
  #   Role.create classification:"0526", description:"Tax Law Specialist                                "
  #   Role.create classification:"1412", description:"Tax Technician                                    "
  #   Role.create classification:"1083", description:"Technical Information Service                     "
  #   Role.create classification:"0391", description:"Technical Writing and Editing                     "
  #   Role.create classification:"2502", description:"Telecommunications                                "
  #   Role.create classification:"0390", description:"Telecommunications Mechanic                       "
  #   Role.create classification:"0382", description:"Telecommunications Processing                     "
  #   Role.create classification:"3919", description:"Telephone Operating                               "
  #   Role.create classification:"5235", description:"Television Equipment Operating                    "
  #   Role.create classification:"5439", description:"Test Range Tracking                               "
  #   Role.create classification:"5446", description:"Testing Equipment Operating                       "
  #   Role.create classification:"1384", description:"Textile Equipment Operating                       "
  #   Role.create classification:"1054", description:"Textile Technology                                "
  #   Role.create classification:"0648", description:"Theater Specialist                                "
  #   Role.create classification:"3604", description:"Therapeutic Radiology Technician                  "
  #   Role.create classification:"4639", description:"Tile Setting                                      "
  #   Role.create classification:"4840", description:"Timber Working                                    "
  #   Role.create classification:"3417", description:"Tool and Equipment Repairing                      "
  #   Role.create classification:"3416", description:"Tool Grinding                                     "
  #   Role.create classification:"6904", description:"Toolmaking                                        "
  #   Role.create classification:"0415", description:"Tools and Parts Attending                         "
  #   Role.create classification:"5705", description:"Toxicology                                        "
  #   Role.create classification:"1140", description:"Tractor Operating                                 "
  #   Role.create classification:"2130", description:"Trade Specialist                                  "
  #   Role.create classification:"1712", description:"Traffic Management                                "
  #   Role.create classification:"3833", description:"Training Instruction                              "
  #   Role.create classification:"2102", description:"Transfer Engraving                                "
  #   Role.create classification:"2110", description:"Transportation Clerk and Assistant                "
  #   Role.create classification:"2135", description:"Transportation Industry Analysis                  "
  #   Role.create classification:"2150", description:"Transportation Loss-Damage Claims Examiner        "
  #   Role.create classification:"2101", description:"Transportation Operation                          "
  #   Role.create classification:"2199", description:"Transportation Specialist                         "
  #   Role.create classification:"5800", description:"Transportation Student Trainee                    "
  #   Role.create classification:"5700", description:"Transportation/Mobile Equipment Maintenance       "
  #   Role.create classification:"5042", description:"Transportation/Mobile Equipment Operation         "
  #   Role.create classification:"0994", description:"Tree Trimming and Removing                        "
  #   Role.create classification:"0106", description:"Unemployment Compensation Claims Examiner         "
  #   Role.create classification:"0082", description:"Unemployment Insurance                            "
  #   Role.create classification:"3106", description:"United States Marshal                             "
  #   Role.create classification:"5406", description:"Upholstering                                      "
  #   Role.create classification:"4742", description:"Utility Systems Operating                         "
  #   Role.create classification:"4820", description:"Utility Systems Repairing Operating               "
  #   Role.create classification:"0996", description:"Vending Machine Repairing                         "
  #   Role.create classification:"0701", description:"Veterans Claims Examining                         "
  #   Role.create classification:"0799", description:"Veterinary Medical Science                        "
  #   Role.create classification:"1084", description:"Veterinary Student Trainee                        "
  #   Role.create classification:"1715", description:"Visual Information                                "
  #   Role.create classification:"0540", description:"Vocational Rehabilitation                         "
  #   Role.create classification:"0249", description:"Voucher Examining                                 "
  #   Role.create classification:"7420", description:"Wage and Hour Compliance                          "
  #   Role.create classification:"6900", description:"Waiter                                            "
  #   Role.create classification:"5408", description:"Warehousing and Stock Handling                    "
  #   Role.create classification:"5409", description:"Wastewater Treatment Plant Operating              "
  #   Role.create classification:"5424", description:"Water Treatment Plant Operating                   "
  #   Role.create classification:"3703", description:"Weighing Machine Operating                        "
  #   Role.create classification:"0894", description:"Welding                                           "
  #   Role.create classification:"0486", description:"Welding Engineering                               "
  #   Role.create classification:"0485", description:"Wildlife Biology                                  "
  #   Role.create classification:"5335", description:"Wildlife Refuge Management                        "
  #   Role.create classification:"2504", description:"Wind Tunnel Mechanic                              "
  #   Role.create classification:"2500", description:"Wire Communications Cable Splicing                "
  #   Role.create classification:"4605", description:"Wire Communications Equipment and Installation and"
  #   Role.create classification:"4600", description:"Wood Crafting                                     "
  #   Role.create classification:"4604", description:"Wood Work                                         "
  #   Role.create classification:"4618", description:"Wood Working                                      "
  #   Role.create classification:"0313", description:"Woodworking Machine Operating                     "
  #   Role.create classification:"0991", description:"Work Unit Supervising                             "
  #   Role.create classification:"1082", description:"Worker's Compensation Claim Examining             "
  #   Role.create classification:"0410", description:"Writing and Editing                               "
                                            